#!/usr/bin/expect -f

set script_path [info script]
set script_dir [file dirname "$script_path"]
set neo_cli_dir [file normalize "$script_dir/.."]
set wallet_path [lindex $argv 0]
set wallet_password [lindex $argv 1]
set timeout -1

cd "$neo_cli_dir"

spawn dotnet neo-cli.dll /rpc

expect "neo>"
send "open wallet ${wallet_path}\n"
expect "password:"
send "${wallet_password}\n"
expect "neo>"
send "start consensus\n"
expect "OnStart"

interact
